# Site settings
title: Open Savannah
email: yall@opensavannah.org
description: We play with data and deploy civic apps.
url: "http://jolly-banana.cloudvent.net"
twitter_username: open_savannah
github_username:  opensavannah
paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown



